### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by lockjohn** [lockjohn/eventdark#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers: login/signup, basic splash page structure
- [x] Styling to match clone
- [x] Demo User
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by lockjohn** [comment]
I need to tweak the demo button so it works from both login and sign up page and need to fix the placeholder text.

**Comment by lockjohn** [comment]
* Pushed update to heroku that fixes above issues  - though my demo button is taking two clicks. will circle back to this later.

**Comment by evhumphrey** [comment]
Nice job, looks awesome! I have some feedback: 

- [ ] Adjust the padding of your inputs; right now when you add test, it's right on the left edge of the input, which looks strange (hint: use `box-sizing: border-box` on `session-form` class, otherwise, adjusting the padding will cause your input fields to grow).
- [ ] I would add a bit more spacing between the errors and the bottom input.
- [ ] Don't use `<br>` tags to accomplish styling; this is an anti pattern. Instead, use margin top or bottom. This includes removing the one in between your buttons
- [ ] Two click demo issue (which you mentioned above) 
- [ ] I would your sign in nav div to an a tag instead, with the class `nav-link`. This will make it so you don't have to click on the text, but can click on the whole 'button'

Here's a screenshot for the form styling I mentioned:
![screen shot 2018-08-10 at 11 51 22 am](https://user-images.githubusercontent.com/6361824/43976571-eaff0a30-9c95-11e8-813d-03d30377db3c.png)

**Comment by lockjohn** [comment]
When I try to wrap my <Link> component in an <a> tag it gives me an error and says Link can't be a child of <a>

**Comment by evhumphrey** [comment]
Two click demo is hard to replicate, marking as complete 🎉
